using System.Collections.Generic;

namespace MedicationTracker
{
    public static class ListOfMedicaments
    {
        public static List<string> Medicaments { get; set; } = new List<string>()
        {
            "Abilify",
            "Aripiprazolum",
            "Absenor",
            "Acespargin",
            "Betalan",
            "Betanil forte",
            "Betaserc",
            "Betesda",
            "Choligrip na noc",
            "Cinie",
            "Cinnarizinum",
            "Cipramil",
            "Circadin",
            "Egolanza",
            "Elenium",
            "Elicea",
            "Elicea Q-Tab",
            "Eliptus",
            "Gripex",
            "Gripex Control",
            "Gripex HotActiv",
            "Gripex HotActiv Forte",
            "Gripex Max",
            "Gripex Noc",
            "Hyperherba",
            "Hyperosedat",
            "Hypnogen",
            "Imigran",
            "Imovane",
            "Instanyl",
            "Karbagen",
            "Katadolon",
            "Kefrenex",
            "Keppra",
            "Lekosen",
            "Lenuxin",
            "Leponex",
            "Microser",
            "Migpriv",
            "Milgamma N",
            "Nivalin",
            "Noax uno",
            "Noctofer",
            "Nodir",
            "Olzin",
            "Olanzapinum",
            "Onirex",
            "Oratram",
            "Orfiril",
            "Petylyl",
            "Pexopar",
            "Pezilgen",
            "Sycrest",
            "Symelon",
            "Symepezil",
            "Symescital",
            "Theraflu ExtraGRIP",
            "Theraflu Zatoki",
            "Tianesal",
            "Tiaprid PMCS",
            "Zolerilis",
            "Zolmiles",
            "Zolmitriptan Stada"
        };
    }
}